{% set name = "sigima" %}
{% set version = "1.0.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 0019d9877e87ab2936e8b68bda7a36f21695e510d9a167c655056dd6b632fddf

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - pip
  run:
    - python >={{ python_min }}
    - guidata >=3.13
    - packaging >=21.3
    - numpy >=1.22,<2.5
    - scipy >=1.10.1,<1.17
    - scikit-image >=0.19.2,<0.27
    - pandas >=1.4,<3.0
    - pywavelets >=1.2,<2.0
    - makefun >=1.13.1
    - typing_extensions >=4.0

test:
  imports:
    - sigima
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  summary: Scientific computing engine for 1D signals and 2D images, part of the DataLab open-source platform.
  home: https://github.com/DataLab-Platform/Sigima/
  description: |
    Sigima is an advanced Python library for scientific image and signal processing. It provides a wide range 
    of functionalities for analyzing and processing data, including signal filtering, image enhancement, and 
    feature extraction. Sigima is based on a simple but effective object-oriented design, making it easy to 
    use and extend.
  doc_url: https://sigima.readthedocs.io/
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - PierreRaybaut
