{% set name = "sigima" %}
{% set version = "1.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: b3b2abe13a03a2371d6aca271beb0851e5929bfe855e71e357da6c62ed03d8ad

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - pip
  run:
    - python >={{ python_min }}
    - guidata >=3.13
    - packaging >=21.3
    - scipy >=1.10.1
    - scikit-image >=0.19.2
    - pandas >=1.4
    - pywavelets >=1.2
    - makefun >=1.13.1
    - typing_extensions

test:
  imports:
    - sigima
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  summary: Scientific computing engine for 1D signals and 2D images, part of the DataLab open-source platform.
  home: https://github.com/DataLab-Platform/Sigima/
  description: |
    Sigima is an advanced Python library for scientific image and signal processing. It provides a wide range 
    of functionalities for analyzing and processing data, including signal filtering, image enhancement, and 
    feature extraction. Sigima is based on a simple but effective object-oriented design, making it easy to 
    use and extend.
  doc_url: https://sigima.readthedocs.io/
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - PierreRaybaut
